mosquitto start script added

diff --git a/prebuild_lan8651_customizations_clean.patch b/prebuild_lan8651_customizations_clean.patch
--- a/prebuild_lan8651_customizations_clean.patch
+++ b/prebuild_lan8651_customizations_clean.patch
@@ -429,4 +429,69 @@ index abcdef1234567890abcdef1234567890abcdef12..fedcba0987654321fedcba0987654321
 +	source "package/lan8651-kernel-config/Config.in"
 	source "package/libostree/Config.in"
 
-
+diff --git a/board/mscc/common/rootfs_overlay/etc/init.d/S80mosquitto b/board/mscc/common/rootfs_overlay/etc/init.d/S80mosquitto
+new file mode 100755
+index 0000000000000000000000000000000000000000..1234567890abcdef1234567890abcdef12345678
+--- /dev/null
++++ b/board/mscc/common/rootfs_overlay/etc/init.d/S80mosquitto
+@@ -0,0 +1,60 @@
++#!/bin/sh
++#
++# Start/stop mosquitto MQTT broker
++#
++
++DAEMON="mosquitto"
++PIDFILE="/var/run/mosquitto.pid"
++CONFIG="/etc/mosquitto/mosquitto.conf"
++
++start() {
++    printf "Starting $DAEMON: "
++    
++    # Create mosquitto user and group if they don't exist
++    if ! id mosquitto > /dev/null 2>&1; then
++        adduser -D -H -s /bin/false mosquitto
++    fi
++    
++    # Create persistence directory
++    mkdir -p /var/lib/mosquitto
++    chown mosquitto:mosquitto /var/lib/mosquitto
++    
++    # Create pid directory
++    mkdir -p /var/run
++    
++    start-stop-daemon -S -q -p $PIDFILE -c mosquitto:mosquitto -x /usr/sbin/$DAEMON -- -c $CONFIG -d
++    if [ $? = 0 ]; then
++        echo "OK"
++    else
++        echo "FAIL"
++    fi
++}
++
++stop() {
++    printf "Stopping $DAEMON: "
++    start-stop-daemon -K -q -p $PIDFILE
++    if [ $? = 0 ]; then
++        echo "OK"
++    else
++        echo "FAIL"
++    fi
++    rm -f $PIDFILE
++}
++
++case "$1" in
++    start)
++        start
++        ;;
++    stop)
++        stop
++        ;;
++    restart|reload)
++        stop
++        start
++        ;;
++    *)
++        echo "Usage: $0 {start|stop|restart}"
++        exit 1
++esac
++
++exit $?
